### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.tablemi.flutter_bluetooth_basic.DeviceConnFactoryManager.sendDataImmediately(java.util.Vector)' on a null object reference

### ISSUE THREAD

**Issue by apocalipse9** [andrey-ushakov/flutter_bluetooth_basic#29]
Hi Folks, good day.
I'm getting this messages on crashlytics and can't reproduce this problem.
Does anyone have any idea what might be causing this problem? In my tests it runs perfectly, but some users are having this problem.

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.tablemi.flutter_bluetooth_basic.DeviceConnFactoryManager.sendDataImmediately(java.util.Vector)' on a null object reference
       at com.tablemi.flutter_bluetooth_basic.FlutterBluetoothBasicPlugin$4.run(:62)
       at com.tablemi.flutter_bluetooth_basic.ThreadPool$1.run(:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)

**Comment by ebrahimmansur** [comment]
same here ,,,,have you found a solution
